name: Tests

on:
  push:
    branches:
      - main
      - v*
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        python: ['3.12', '3.13', '3.14']
        sofistik: ['2022', '2023', '2024', '2025']

    name: "Python ${{ matrix.python }} / ${{ matrix.os }} / SOFiSTiK ${{ matrix.sofistik }}"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Download SOFiSTiK DLLs
        env:
          GH_TOKEN: ${{ secrets.SOFISTIK_DLL_TOKEN }}
        shell: bash
        run: |
          gh repo clone StudioWEngineers/SOFiSTiK-DLLs sofistik_dlls

      - name: Download SOFiSTiK CDBs
        env:
          GH_TOKEN: ${{ secrets.SOFISTIK_CDB_TOKEN }}
        shell: bash
        run: |
          gh repo clone StudioWEngineers/SOFiSTiK-CDBs sofistik_cdbs

      - name: Set SOFiSTiK DLL path
        shell: pwsh
        run: |
          $cdbPath = "${{ github.workspace }}\sofistik_cdbs\cdb_files\"
          $dllPath = "${{ github.workspace }}\sofistik_dlls\${{ matrix.sofistik }}"
          echo "SOFISTIK_CDB_PATH=$cdbPath" >> $env:GITHUB_ENV
          echo "SOFISTIK_DLL_PATH=$dllPath" >> $env:GITHUB_ENV
          echo "SOFISTIK_VERSION=${{ matrix.sofistik }}" >> $env:GITHUB_ENV
          echo $cdbPath >> $env:GITHUB_PATH
          echo $dllPath >> $env:GITHUB_PATH

      - name: Run tests (SOFiSTiK ${{ matrix.sofistik }})
        run: |
          python -m unittest discover -s tests -p "test_*.py" --verbose
